#Cherry Blossom Kitty Theme
#copy file to ~.config/kitty/
# add this line to ~.config/kitty/kitty.conf: include ./Cherry_Blossom.conf

background            #200d0b
background_opacity    0.82

foreground            #faa7ce        #default=white

cursor                #fffefe

selection_background  #FFC0CB
selection_foreground  #40061c

#default=black
color0                #302b2a
color8                #4d4d47

#default=red
color1                #a6473d
color9                #ff0314

#default=green
color2                #577644
color10               #129c20

#default=yellow
color3                #9c6f2a
color11               #fc5a21

#default=blue
color4                #486a97
color12               #7878f7

#default=magenta
color5                #854552
color13               #fc89a4

#default=cyan
color6                #9c815e
color14               #fad385

#default=white
color7                #c8c8c8
color15               #fffefe
